spring:
    datasource:
        platform: mysql
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/springtest?useUnicode=true&characterEncoding=UTF-8
        username: root
        password: pass
    jpa:
        show-sql: true
#        hibernate.ddl-auto: create-drop
        hibernate.naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
        dialect: org.hibernate.dialect.MySQL5Dialect
        database: MYSQL
    data:
        mongodb:
            uri: mongodb://localhost/testmongo
#application:
#    ldap:
#       url: LDAP://192.168.28.123:389
#       userName: syni@dlp.com
#       password: q1w2E#R$
#application:
#    ldap:
#       url: LDAP://192.168.28.183:389
#       userName: test1@advdbg.org
#       password: q1w2E#R$
---
spring:
    profiles: DevTest
    datasource:
        platform: hsqldb
        driver-class-name: org.hsqldb.jdbcDriver
        url: jdbc:hsqldb:mem:testdb
        initialize: true
    jpa:
        hibernate.ddl-auto: create-drop
        hibernate.naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
        show-sql: true
        database: HSQL
    data:
        mongodb:
            uri: mongodb://localhost/syni